"""PKI management for forward-proxy MITM TLS termination.

The module implements the cryptographic foundation of forward-proxy mode:
generating its own root CA and leaf certificates signed by it for individual
hosts. The forward-proxy itself (accepting CONNECT, TLS termination based on
the certificates issued here, blind tunneling for the remaining hosts) is
implemented separately and is not touched by this module -- here only
certificate issuance and storage.

Trust model and security (read before use)
----------------------------------------------------------------
The root CA generated by this module is able to sign certificates for
ANY host, and therefore to decrypt TLS traffic (man-in-the-middle) for any
client that agrees to trust this CA. The CA private key (the
``rootCA-key.pem`` file) IS that capability to issue such certificates,
so it must NEVER leave the user's machine: do not log it, do not send it
over the network, do not commit it to a repository.

The module does NOT install or offer to install this CA into the OS's or
browser's trusted root certificate store. The only trust channel provided
is the ``NODE_EXTRA_CA_CERTS`` environment variable, pointing at the PEM
file of the root certificate (see
:meth:`CertificateAuthority.root_certificate_path`). It extends the set of
trusted CAs only for a single Node.js process (the one Claude Code runs in)
and affects neither OS-wide trust nor other processes. The moment and the
process for which this variable is set is decided by calling code outside
this module -- the module itself makes no such decision.
"""

from __future__ import annotations

import datetime
import os
import threading
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

# RSA is chosen over EC for maximum compatibility with the unpredictable set
# of TLS clients that will end up behind the forward-proxy (different
# versions of Node.js, curl, language HTTP libraries): RSA-2048 is supported
# by practically any TLS stack, whereas support for specific EC curves on
# older or trimmed-down builds is less guaranteed. 2048 bits is the lower
# bound still considered secure (NIST SP 800-57), and comfortably enough for
# a key that lives within a local dev tool.
_KEY_SIZE_BITS = 2048
_PUBLIC_EXPONENT = 65537

# Root CA lifetime. Mature MITM tools (mitmproxy, Charles, Fiddler) keep the
# root CA for years so the user doesn't have to re-register it in
# NODE_EXTRA_CA_CERTS on every reissue. 10 years is common practice for a
# local CA, which is not subject to CA/Browser Forum constraints (those only
# apply to publicly trusted CAs).
_CA_VALIDITY = datetime.timedelta(days=3650)

# The leaf certificate, in contrast, lives briefly: the cache is in-memory
# only (does not survive a process restart), so long validity is not
# needed, and a short lifetime limits the damage from compromising a single
# leaf key -- unlike the CA key, the leaf certificate's private key is not
# protected by file permissions on disk (it exists only in process memory).
_LEAF_VALIDITY = datetime.timedelta(days=30)

# Renewal margin: the certificate is reissued ahead of time, not at the
# moment it actually expires. The router runs as a long-lived process
# (LaunchAgent) and keeps MITM host contexts in a cache -- without a margin
# the cache would keep serving an already-expired certificate right up to
# the first request AFTER expiry, and that request would have to wait for a
# new key to be generated on the handshake path.
_LEAF_RENEWAL_MARGIN = datetime.timedelta(days=1)

# Backdating the leaf certificate's validity start. If the client's clock
# is behind the router machine's clock, ``not_valid_before`` set to exactly
# the current time would fall in the future from the client's point of
# view, and the certificate would be rejected as not yet valid. Mature MITM
# tools (mitmproxy) use the same trick.
_NOT_VALID_BEFORE_SKEW = datetime.timedelta(days=1)

# CN/O are human-recognizable in the OS/browser certificate list -- modeled
# after how mitmproxy ("mitmproxy") and Charles ("Charles Proxy CA") name
# themselves, rather than a generic name like "Root CA".
_CA_COMMON_NAME = "open-harness-router local CA"
_CA_ORGANIZATION_NAME = "open-harness-router"
_CA_ORGANIZATIONAL_UNIT_NAME = "Local development -- do not export or trust system-wide"

_ROOT_CERT_FILENAME = "rootCA.pem"
_ROOT_KEY_FILENAME = "rootCA-key.pem"

_CA_DIR_MODE = 0o700
_PRIVATE_KEY_FILE_MODE = 0o600
_PUBLIC_CERT_FILE_MODE = 0o644


class CertificateAuthorityError(Exception):
    """Error loading, generating, or persisting CA material."""


def _generate_ca_certificate() -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
    """Generate a new private key + self-signed CA certificate pair.

    Returns:
        Tuple of (root CA certificate, root CA private key).
    """
    private_key = rsa.generate_private_key(
        public_exponent=_PUBLIC_EXPONENT, key_size=_KEY_SIZE_BITS
    )
    subject = issuer = x509.Name(
        [
            x509.NameAttribute(NameOID.COMMON_NAME, _CA_COMMON_NAME),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, _CA_ORGANIZATION_NAME),
            x509.NameAttribute(
                NameOID.ORGANIZATIONAL_UNIT_NAME, _CA_ORGANIZATIONAL_UNIT_NAME
            ),
        ]
    )
    now = datetime.datetime.now(datetime.UTC)
    public_key = private_key.public_key()
    certificate = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(public_key)
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + _CA_VALIDITY)
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=False,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(x509.SubjectKeyIdentifier.from_public_key(public_key), critical=False)
        .sign(private_key, hashes.SHA256())
    )
    return certificate, private_key


def _generate_leaf_certificate(
    hostname: str,
    ca_certificate: x509.Certificate,
    ca_private_key: rsa.RSAPrivateKey,
) -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
    """Generate a leaf certificate for the host, signed by the root CA.

    Args:
        hostname: the DNS name of the host the certificate is issued for
            (goes into both CN and subjectAltName -- without SAN modern
            clients like Chrome and Node.js reject the certificate even
            with a correct CN).
        ca_certificate: the root CA certificate (source of the issuer name).
        ca_private_key: the root CA private key that signs the leaf
            certificate.

    Returns:
        Tuple of (leaf certificate, leaf certificate private key).
    """
    private_key = rsa.generate_private_key(
        public_exponent=_PUBLIC_EXPONENT, key_size=_KEY_SIZE_BITS
    )
    subject = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, hostname)])
    now = datetime.datetime.now(datetime.UTC)
    public_key = private_key.public_key()
    certificate = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(ca_certificate.subject)
        .public_key(public_key)
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - _NOT_VALID_BEFORE_SKEW)
        .not_valid_after(now + _LEAF_VALIDITY)
        .add_extension(x509.SubjectAlternativeName([x509.DNSName(hostname)]), critical=False)
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=True,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(
            x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=False
        )
        .add_extension(x509.SubjectKeyIdentifier.from_public_key(public_key), critical=False)
        .add_extension(
            x509.AuthorityKeyIdentifier.from_issuer_public_key(ca_private_key.public_key()),
            critical=False,
        )
        .sign(ca_private_key, hashes.SHA256())
    )
    return certificate, private_key


def _is_expiring_soon(certificate: x509.Certificate) -> bool:
    """Check whether the certificate expires within the renewal margin.

    Args:
        certificate: the leaf certificate being checked.

    Returns:
        True if no more than :data:`_LEAF_RENEWAL_MARGIN` remains until
        ``not_valid_after`` (or it has already expired).
    """
    now = datetime.datetime.now(datetime.UTC)
    return certificate.not_valid_after_utc - now <= _LEAF_RENEWAL_MARGIN


class CertificateAuthority:
    """Holder of the forward-proxy root CA and the leaf certificate cache.

    On creation, either loads an existing CA from disk (``ca_dir``) or
    generates a new one and persists it to disk with restricted access
    permissions. Leaf certificates for individual hosts are cached only in
    process memory -- their short lifetime does not justify persisting them
    across restarts (see :data:`_LEAF_VALIDITY`).
    """

    def __init__(self, ca_dir: Path) -> None:
        """Initialize the CA holder, loading or generating the material.

        Args:
            ca_dir: directory for the root CA's PEM files. Created if it
                does not exist.

        Raises:
            CertificateAuthorityError: if CA files exist on disk but are
                corrupted or do not parse as valid PEM.
        """
        self._ca_dir = ca_dir
        self._cert_path = ca_dir / _ROOT_CERT_FILENAME
        self._key_path = ca_dir / _ROOT_KEY_FILENAME
        self._leaf_cache: dict[str, tuple[x509.Certificate, rsa.RSAPrivateKey]] = {}
        # Protects the check-and-reissue of the leaf certificate: without
        # the lock, two connections arriving for the same host at the same
        # moment of expiry would both see the stale cache and each generate
        # its own certificate -- the second would silently overwrite the
        # first in the cache, and a client that already started the TLS
        # handshake with the first one would get a mismatched certificate
        # for subsequent requests on the same connection.
        self._leaf_cache_lock = threading.Lock()

        if self._cert_path.exists() and self._key_path.exists():
            self._certificate, self._private_key = self._load_from_disk()
        else:
            self._certificate, self._private_key = self._generate_and_persist()

    def _load_from_disk(self) -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
        """Read and parse the existing CA PEM files from disk.

        Returns:
            Tuple of (root CA certificate, root CA private key).

        Raises:
            CertificateAuthorityError: if a file is corrupted, does not
                parse as PEM, or the private key is not an RSA key.
        """
        try:
            certificate = x509.load_pem_x509_certificate(self._cert_path.read_bytes())
            private_key = serialization.load_pem_private_key(
                self._key_path.read_bytes(), password=None
            )
        except (ValueError, OSError) as exc:
            raise CertificateAuthorityError(
                f"failed to load existing CA material from {self._ca_dir}: {exc}"
            ) from exc
        if not isinstance(private_key, rsa.RSAPrivateKey):
            raise CertificateAuthorityError(
                f"CA private key at {self._key_path} is not an RSA private key"
            )
        return certificate, private_key

    def _generate_and_persist(self) -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
        """Generate a new CA and persist it to disk with 0700/0600 permissions.

        ``Path.mkdir``/``Path.write_bytes`` are subject to the process
        umask, so the final permissions are set explicitly via
        ``os.chmod`` after creation -- independent of the current umask.

        Returns:
            Tuple of (root CA certificate, root CA private key).
        """
        self._ca_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(self._ca_dir, _CA_DIR_MODE)

        certificate, private_key = _generate_ca_certificate()

        cert_pem = certificate.public_bytes(serialization.Encoding.PEM)
        key_pem = private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )

        self._key_path.write_bytes(key_pem)
        os.chmod(self._key_path, _PRIVATE_KEY_FILE_MODE)

        self._cert_path.write_bytes(cert_pem)
        os.chmod(self._cert_path, _PUBLIC_CERT_FILE_MODE)

        return certificate, private_key

    def root_certificate_path(self) -> Path:
        """Return the path to the CA root certificate's PEM file.

        The value is intended for the ``NODE_EXTRA_CA_CERTS`` environment
        variable -- it extends trust only for a single Node.js/Claude Code
        process, it is not installed into the system's trusted certificate
        store.

        Returns:
            Path to the root certificate file (PEM, public part -- the CA
            private key is not returned by this method).
        """
        return self._cert_path

    def leaf_certificate_for_host(
        self, hostname: str
    ) -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
        """Return the leaf certificate for the host, reissuing it if needed.

        The cached certificate is reissued ahead of time -- when no more
        than :data:`_LEAF_RENEWAL_MARGIN` remains until expiry, not at the
        moment it actually expires. Without this check, a process living
        longer than :data:`_LEAF_VALIDITY` (the router runs as a long-lived
        service) would start presenting an expired certificate to clients:
        the cache was filled once and never refreshed.

        Args:
            hostname: the DNS name of the host the certificate is needed
                for (used as the CN and as the sole SAN value).

        Returns:
            Tuple of (leaf certificate, leaf certificate private key). The
            method is thread-safe: concurrent calls for the same expiring
            host reissue the certificate exactly once, not once per call.
        """
        with self._leaf_cache_lock:
            cached = self._leaf_cache.get(hostname)
            if cached is not None and not _is_expiring_soon(cached[0]):
                return cached

            leaf = _generate_leaf_certificate(hostname, self._certificate, self._private_key)
            self._leaf_cache[hostname] = leaf
            return leaf
